### ISSUE TITLE
打赏组件及时展示

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/jx3box-common-ui#21]
1. 目前品鉴完后，会立马插入品鉴条目
2. 但是打赏完后，需要刷新才展示

需要在前端做立即插入

**Comment by Kaviilee** [comment]
打赏接口没有返回品鉴详情

品鉴的接口返回
![image](https://user-images.githubusercontent.com/25825282/178134607-f9a3528e-14bf-4fa6-a764-f5e76676e923.png)

打赏的接口返回
![image](https://user-images.githubusercontent.com/25825282/178134616-c456b03a-e055-44ab-afff-adaaacfc0d28.png)
