### ISSUE TITLE
为什么src目录下的模块不单独分文件夹./src/Header 这样引入呢

### ISSUE THREAD

**Issue by wb121017405** [JX3BOX/jx3box-common-ui#3]
参照element-admin的目录结构，到时候模块多起来组件也方便查找区分

**Comment by iRuxu** [comment]
立个flag，公共组件基本写完了，不会再加超过5个。

**Comment by wb121017405** [comment]
![image](https://user-images.githubusercontent.com/22069747/82799804-39888300-9ead-11ea-9db0-73a31080f355.png)
个人认为这样的目录更适合 手动狗头

**Comment by iRuxu** [comment]
终于开始建子目录啦！
