### ISSUE TITLE
称号与勋章拓展

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/jx3box-common-ui#47]
## 需求背景
引用子璇和速花火的反馈

![image](https://github.com/JX3BOX/jx3box-cms/assets/40552272/78035d11-8bb2-4d05-a2c4-7e8ce6dc0311)
现在的勋章不仅仅是百强榜的了，所以需要在对应数据库内新增一个字段，填写点击勋章会跳转的地址（例如对应活动专题页）
另外希望提交的rank_id能为空字符串“”

- [x] 已了解

**Comment by iRuxu** [comment]
## 实现方案

在勋章配置的地方，增加一个字段`url`

然后设置一个跳转规则。

比如  `/event/<%=eventid%>`
到时候通过lodash的模板渲染，来拼接得到正确的链接地址。
os和接口都要改

- [ ] 已完成

**Comment by iRuxu** [comment]
## 用户表

允许rank_id为空

但是茶馆风月录还是id为1
而是type设一个story

就相当于是story的第一届活动
地址可以跳个死的先，未来会做活动专题页（每个活动都有，在event库和rank库，情缘杯会放到rank库）
因为只有活动才会发放勋章和称号

- [ ] 已完成

**Comment by iRuxu** [comment]
## 渲染

jx3box-common-ui  库修改称号和勋章的地址拼接方法

然后子璇在author库上测，测好了没问题后，同步cms栏目（macro/bps/pvp/fb/bbs/tool以后不要我再解释）

- [ ] 已完成

**Comment by Kaviilee** [comment]
> ## 实现方案
> 在勋章配置的地方，增加一个字段`url`
> 
> 然后设置一个跳转规则。
> 
> 比如 `/event/<%=eventid%>` 到时候通过lodash的模板渲染，来拼接得到正确的链接地址。 os和接口都要改
> 
> * [ ]  已完成

没有必要做模板渲染吧，直接写死跳转链接不就ok了？

**Comment by iRuxu** [comment]
## 子璇
配置对应的勋章与称号链接，让子璇确保每个称号链接都正确。

- [ ] 已完成
