### ISSUE TITLE
马甲系统

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/jx3box-common-ui#50]
<img width="484" alt="image" src="https://github.com/user-attachments/assets/da9374b1-7b3c-44d8-a85c-dfd00e181d1c">

- [x] 已完成

**Comment by Kaviilee** [comment]
## 入口
公共头右上角，把资料设置换成【马甲切换】

点击马甲切换，弹出弹窗

弹窗内容
![image](https://github.com/user-attachments/assets/f86f31a9-c2ba-43a5-8e5f-67b23bb9a7ca)

高度600 宽度320
左侧头像
右上昵称
右下上次登录

**Comment by Kaviilee** [comment]
## 逻辑

将token，user等信息，序列化字符串之后，存至jx3box-alternate-1/2/3

**Comment by Kaviilee** [comment]
## 联动

最后一项是 + 号，用于添加一个马甲，点击前往登录页面并且携带alertnate=1参数，account项目参数存在，则登陆成功之后额外存内容和token

**Comment by iRuxu** [comment]
<img width="751" alt="image" src="https://github.com/user-attachments/assets/3979880e-778b-43ae-a0f7-1e1712f775db">

- [ ] 已完成

**Comment by iRuxu** [comment]
首次添加马甲逻辑存在问题

我现在还没有任何马甲的时候，当我点击切换马甲触发时，就得把当前的账号作为马甲塞进去啊

- [ ] 已完成

**Comment by iRuxu** [comment]
<img width="586" alt="image" src="https://github.com/user-attachments/assets/7038109a-879b-42d1-9bd0-dd6587725876">

- [ ] 已完成

**Comment by iRuxu** [comment]
<img width="562" alt="image" src="https://github.com/user-attachments/assets/f92283e4-8116-49ce-827c-b0daa5dd5871">

- [ ] 已完成
